time = 0
wait_time = 0
next_redraw = 0
userinp = nil
next_challenge = nil
current_challenge = nil
current_answer = nil
current_answer_valid = false
current_result_number = 0
current_x = nil
counters = { }
on_click = nil
on_update = nil
results = { }
