time = 0
wait_time = 0
next_redraw = 0
userinp = nil
next_challenge = nil
current_challenge = nil
current_answer = nil
current_answer_valid = false
current_result_number = 0
current_bonus_size = nil
current_x = 0
current_y = 0
counters = { }
on_click = nil
on_update = nil
on_draw = nil
results = { }
challenge_renderer = { }
